[main]
# We're setting the font to "Dita Sweet", which is an Art Deco font available in the AUR.
font=Dita Sweet:size=16
prompt="> "
lines=10
width=30

[colors]
# Colors are in RGBA format (Red, Green, Blue, Alpha)
background=3b5b7559    # BioShock 2 outdoor underwater cyan
text=ffffffff          # White font
match=d4af37ff         # Brass/Gold for matching search letters
selection=006666ff     # Lighter cyan for the highlighted selection
selection-text=ffffffff
selection-match=d4af37ff
border=0c3a48ff        # Dark cruel hopeless deep sea cyan (slightly lighter)

[border]
width=3
radius=0
