---
- name: Find all stow packages
  find:
    paths: "{{ playbook_dir }}/../stow"
    file_type: directory
  register: stow_dirs

- name: Stow all dotfiles
  command: "stow -R -t {{ ansible_env.HOME }} -d {{ playbook_dir }}/../stow {{ item.path | basename }}"
  loop: "{{ stow_dirs.files }}"
  changed_when: true
