[window]
opacity = 0.6

[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
size = 12.0
